### ISSUE TITLE
npmjs.org repository shows latest version as 0.0.2

### ISSUE THREAD

**Issue by jrpilat** [rosshinkley/nightmare-iframe-manager#11]
The latest published version of **nightmare-iframe-manager** on [npmjs.org](https://www.npmjs.com/package/nightmare-iframe-manager) is 0.0.2, last updated 2016-08-04.  I kindly request that 0.0.4 be published in order to propagate [fixes for incompatibility with nightmare 2.8](https://github.com/rosshinkley/nightmare-iframe-manager/pull/8).  Thanks!

**Comment by bluesockets** [comment]
👍

**Comment by highvoltag3** [comment]
+1

**Comment by highvoltag3** [comment]
Anyone pretty please? 😂
Anyone waiting you can sort to this in the mean time `npm install rosshinkley/nightmare-iframe-manager`

**Comment by rosshinkley** [comment]
The NPM package is not owned by me.  I refrained from publishing it on purpose.  The publisher has granted me collaborator rights and I've updated the package.  Closing.

**Comment by highvoltag3** [comment]
@rosshinkley May I ask why did you refrain from publishing it? if it's because of the warning you clearly made on the README, what option do you think it's best to accomplish what this package is currently doing for it's users?
