### ISSUE TITLE
The module doesn't modify the Nightmare object

### ISSUE THREAD

**Issue by tiangolo** [rosshinkley/nightmare-iframe-manager#2]
If I run it with the instructions in the example:

``` javascript
require('nightmare-iframe-manager');
var nightmare = Nightmare();
nightmare.goto('http://example.com')
  .enterIFrame('#someIFrame')
  .title()
  .then(function(title){
    // `title` is the title of the child frame #someIFrame
  })

```

The `Nightmare` object doesn't exist yet.

If I add

``` javascript
var Nightmare = require('nightmare');
```

The `Nightmare` object doesn't get the new methods: `.enterIFrame(selector)`, etc. (They don't show up inside `Nightmare.prototype`).

I tried adding the `var Nightmare = require('nightmare')` before and after the `require('nightmare-iframe-manager');` but it didn't worked.

---

Also, looking at the code, I see that there's no `module.exports`, I guess that the module is using its own Nightmare and the rest of the application is using another Nightmare.

I think that using a `module.exports` with a function that takes as a parameter a `Nightmare` object and returns it modified could work. If you want I can try a PR with that.

Calling it would end up something like:

``` javascript
var Nightmare = require('nightmare');
var nightmareIframeManager = require('nightmare-iframe-manager');

var Nightmare = nightmareIframeManager(Nightmare);

var nightmare = Nightmare();
```

Or more shortly like:

``` javascript
var Nightmare = require('nightmare-iframe-manager')(require('nightmare'));

var nightmare = Nightmare();
```

**Comment by rosshinkley** [comment]
This is how pretty much all of my other Nightmare modules work, and this one didn't get updated.  Should be fixed shortly.

**Comment by tiangolo** [comment]
Great! Thanks for taking the time to fix it.
