### ISSUE TITLE
Does not work in Nightmare >=2.8.0

### ISSUE THREAD

**Issue by lucamartinetti** [rosshinkley/nightmare-iframe-manager#7]
Does not work after 

> changes in .evaluate() to allow for asynchronous execution

Possibly because of this arity check?

https://github.com/rosshinkley/nightmare/blob/a85d4f8c25a75cbaad55afa001f89e1a5efb4303/lib/javascript.js#L21

**Comment by rosshinkley** [comment]
Yep.  Sounds like that's the case.
